apiVersion: rejdeboer.com.github.com/v1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: cluster-sample
spec:
  # TODO(user): Add fields here
